branch: true
ignore-not-existing: true
llvm: true
filter: covered
ignore:
  - "/*"
  - "C:/*"
  - "../*"
keep-only:
  - "./src/*"
excl-line: "#\\[derive\\("
excl-br-line: "#\\[derive\\("
excl-start: "mod tests \\{"
excl-br-start: "mod tests \\{"
parallel: true